### PR TITLE
Publish on gentoo linux

### PR DESCRIPTION
**Pull request by MustafaSalih1993**
I [published](https://github.com/gentoo/guru/tree/master/media-gfx/sic) **sic** on Gentoo Linux GURU overlay,
and added myself as a maintainer for the ebuild since its a community overlay(repository),i will keep it in sync with every GitHub release, 
the commits are just to keep the fork in sync with the upstream, the actual changes is just in the README file in the installation section
PS: of course there's no hard feelings if you decided not to merge this PR

### CODE REVIEW

**Comment by foresterre** [comment]
Happy to add it 😄.

**Review by foresterre — CHANGES_REQUESTED** [review]
Could you please rebase it against the latest `main` branch? Otherwise LGTM

**Comment by MustafaSalih1993** [comment]
Hello foresterre
i already did merge rebase with github and gave me that list of commits.
after your comment, i checked my local fork and this is the output
```sh
$git checkout publish-on-gentoo-linux
$git fetch upstream
$git merge upstream/main
> Already up to date.
```
i think i need to read the git documentation :D

**Comment by foresterre** [comment]
Looking at `git log --all --decorate --oneline --graph` it looks like our main branches do not line up nicely; although I'm not sure yet why it happened.

```
| * b1c7ac6 Test coverage for sic
| *   bd4dcd2 Merge pull request #844 from foresterre/horizontal-gradient-docs
| |\
| | * 7e5edc0 Add horizontal-gradient to the changelog
| | * 7ca0ce2 Add horizontal-gradient to the docs
| |/
| *   b2d2470 Merge pull request #840 from MustafaSalih1993/horizontal-gradient
| |\
| | * b492a44 (origin/horizontal-gradient) cleanup/fixes for the review
| | * 1793e20 added blending functionality to horizontal-gradient
| | * 8bbe4bf added horizontal-gradient option #571
| |/
| | * 74fa701 (origin/publish-on-gentoo-linux) published on gentoo linux GURU overlay <--- HERE is the commit we want
| |/
|/|
* | d139d0c Bump syn from 1.0.67 to 1.0.68
```

I forked your version of the repo, and did the following to get a branch in a workable state:
```
git remote add upstream git@github.com:foresterre/sic.git # you already have this
git checkout upstream/main # now we have my current main branch in a detached state
git switch -c published-on-gentoo # create a branch for it
git cherry-pick 74fa701 # cherry pick your commit
git push origin published-on-gentoo
```
Then you can re-open the PR from this new branch. I think doing this will be faster, although maybe less satisfying, than fixing the current branch.

**Comment by MustafaSalih1993** [comment]
Ahh, this mess made when i did a compare-between-forks on GitHub and then made a pull request,
sorry for this bad PR I'm still learning git, I'll try to fix it

**Comment by foresterre** [comment]
Don't worry, I'm happy to help 😄. Feel free to ask if there's something I can do to help further :).

**Comment by MustafaSalih1993** [comment]
> Don't worry, I'm happy to help smile. Feel free to ask if there's something I can do to help further :).

Thanks :D 
ahh i tried to revert back to a 74fa701 and merge upstream/main then pushed,
i give up, i'll close this and make a new branch as you suggested :'(

**Pull request closed without merging**
